### ISSUE TITLE
Possible LUA errors

### ISSUE THREAD

**Issue by Whovian9369** [rohieb/mpv-notify#6]
Long story short: I don't know if this is my end or yours, and for that I apologize now.

The error, when loaded via the `lua=~/.mpv/lua/notify.lua` is as follows:

```
Warning: option --lua was replaced with --script and might be removed in the future.
[notify] 
[notify] stack traceback:
[notify]    /home/jared/.mpv/lua/notify.lua:70: in main chunk
[notify]    [C]: at 0x00475400
[notify]    [C]: at 0x004769a0
[notify] Lua error: /home/jared/.mpv/lua/notify.lua:70: module 'socket.http' not found:
[notify]    no field package.preload['socket.http']
[notify]    no file './socket/http.lua'
[notify]    no file '/usr/share/luajit-2.0.4/socket/http.lua'
[notify]    no file '/usr/local/share/lua/5.1/socket/http.lua'
[notify]    no file '/usr/local/share/lua/5.1/socket/http/init.lua'
[notify]    no file '/usr/share/lua/5.1/socket/http.lua'
[notify]    no file '/usr/share/lua/5.1/socket/http/init.lua'
[notify]    no file './socket/http.so'
[notify]    no file '/usr/local/lib/lua/5.1/socket/http.so'
[notify]    no file '/usr/lib/lua/5.1/socket/http.so'
[notify]    no file '/usr/local/lib/lua/5.1/loadall.so'
[notify]    no file './socket.so'
[notify]    no file '/usr/local/lib/lua/5.1/socket.so'
[notify]    no file '/usr/lib/lua/5.1/socket.so'
[notify]    no file '/usr/local/lib/lua/5.1/loadall.so'

```

An image of the error:
![2016-07-15-172124_632x464_scrot](https://cloud.githubusercontent.com/assets/5240754/16889051/ca67c16e-4ab1-11e6-8a3d-9d76a4e71c97.png)

mpv --version returns:

```
mpv git-8b47e5d (C) 2000-2016 mpv/MPlayer/mplayer2 projects
 built on Tue Jul 12 15:40:06 EDT 2016
ffmpeg library versions:
   libavutil       55.17.103
   libavcodec      57.24.102
   libavformat     57.25.100
   libswscale      4.0.100
   libavfilter     6.31.100
   libswresample   2.0.101
ffmpeg version: 3.0.2

```

I'm running on Arch Linux, and that's really the most that I can give ya there.

Any more info will be added as requested! :)

**Comment by rohieb** [comment]
On 15.07.2016 23:31, Whovian9369 wrote:

> [notify] Lua error: /home/jared/.mpv/lua/notify.lua:70: module 'socket.http' not found:

You'll need to install LuaSocket, either [from
source](http://w3.impa.br/~diego/software/luasocket/installation.html)
or from your package manager. (Yes, this should have been documented in
the README...)
- Roland

**Comment by Whovian9369** [comment]
Well thanks for your time! I'm not the best at reading, it appears.
